apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler-debug
  namespace: kube-system
spec:
  nodeName: scheduler5g-dev-control-plane
  hostNetwork: true
  restartPolicy: Never
  containers:
  - name: kube-scheduler-debug
    image: registry.k8s.io/kube-scheduler:v1.34.0
    command:
    - kube-scheduler
    - --kubeconfig=/etc/kubernetes/admin.conf
    - --config=/etc/kubernetes/scheduler-config.yaml
    - --v=4
    volumeMounts:
    - name: admin-kubeconfig
      mountPath: /etc/kubernetes/admin.conf
      subPath: admin.conf
      readOnly: true
    - name: scheduler-config
      mountPath: /etc/kubernetes/scheduler-config.yaml
      subPath: scheduler-config.yaml
      readOnly: true
  volumes:
  - name: admin-kubeconfig
    hostPath:
      path: /etc/kubernetes
      type: Directory
  - name: scheduler-config
    hostPath:
      path: /etc/kubernetes
      type: Directory
