apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  labels:
    pod_type: UPF
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi


